### PR TITLE
Logical types in unions and complex schemas

### PR DESCRIPTION
**Pull request by kkirsanov**
Working with complex schemas, I found the incorrect matching of logical types during validation. This commit fixes this.

### CODE REVIEW

**Comment by kkirsanov** [comment]
ups. Very strange behavior on 2.6.

Need to investigate.

**Comment by kkirsanov** [comment]
@tebeka 
Can i merge this using Squah@merge?

**Comment by kkirsanov** [comment]
I`m new to github.

Should i Sqash or rebase?

**Comment by tebeka** [comment]
There's a "squash & merge" option, doing it.

**Pull request merged**
