### PR TITLE
allow for schema migration in the schemaless reader

### PR DESCRIPTION
**Pull request by scottbelden**
Resolves https://github.com/tebeka/fastavro/issues/176

### CODE REVIEW

**Comment by scottbelden** [comment]
@abrarsheikh Let me know if this will work for you regarding https://github.com/tebeka/fastavro/issues/176. You will still need the original schema that was used to write out the avro binary, but now you can supply the new reader schema to handle new fields and other schema migration.

**Comment by abrarsheikh** [comment]
@scottbelden thanks for picking this up, does this fully support [schema resolution](https://avro.apache.org/docs/1.8.1/spec.html#Schema+Resolution) with schemaless reader? 

can you point me to some docs that talk about the difference between  `writer`/`reader` and `schemaless_writer`/`schemaless_reader` ?

**Comment by scottbelden** [comment]
The current released version of fastavro doesn't support schema resolution in the schemaless reader/writer. Schema resolution is supported with the normal reader/writer.

Typically when writing avro binary with the normal writer, it includes the standard avro header, metadata, and then finally all of the record data (for one or more records). To read the encoded data you don't need to provide the schema that was used to write the data because that schema was included in the binary output. Of course, if the schema has changed you would need to provide the new `reader_schema` so that proper resolution can be done.

In the case of the schemaless reader/writer, only the data is encoded, not all the other information like the schema, headers, etc. This means that when you go to read the data, you need to provide the schema that was used when it was encoded. Both sides must agree on what schema was used for the data. One of the use cases for something like this is two network endpoints that want to reduce the size of the data being transmitted between them (to conserve bandwidth). Since the headers and schema (which could be quite large) is not included, the total binary is smaller, but once again, both parties need to know what schema was used during writing.

This change would allow the `schemaless_reader` to supply an updated `reader_schema` (in addition to still needing to supply the original schema that was used for writing) to allow for schema migration/resolution.

**Comment by abrarsheikh** [comment]
@scottbelden awesome. Thanks a lot for the context, i now have a better understanding of how this work. I am going to take a stab at this code review today

**Comment by abrarsheikh** [comment]
lg2n, ship it

**Comment by abrarsheikh** [comment]
thanks, is this feature released in `0.18.2`?

**Comment by scottbelden** [comment]
Yes, it should be.

**Pull request merged**
