### PR TITLE
ujson usage in case if installed

### PR DESCRIPTION
**Pull request by lemurchik**
There is simplejson usage in fastavro/writer.py file i think it's better to use ujson and use it not only in writer.

I'm not sure how to write about it in README.md because information about simplejson in writer wasn't reflected there.

https://github.com/esnme/ultrajson#ultrajson

### CODE REVIEW

**Comment by tebeka** [comment]
Thanks! Do you have some benchmarks to show the speedup gained from using ujson on Avro files?

**Comment by lemurchik** [comment]
I've tired to do benchmarks with your tessts/benchmark.py and all avro files in tests/avro-files/
```
time ls -f avro-files/*.avro | while read -r file; do python benchmark.py $file; done
```

With python2.7 overall execution time for ujson was about 1.06+ s and for json about 1.1+. So it was at list 0.04s faster

If you'll give me file benchmark.avro file that is mentioned in .gitignore file I could try to do benchmarking better.

**Comment by tebeka** [comment]
I don't seem to have it anymore :( I'll try to find a good avro file for benchmarking.

**Comment by lemurchik** [comment]
Thanks, it would be great!

**Comment by tebeka** [comment]
@scottbelden, @kkirsanov Can you cook up some good Avro benchmark? Maybe there's something in the main Avro repository?

**Comment by scottbelden** [comment]
I'll try to take a look but I'm pretty busy so I might not be able to until next week. I'll see if I can squeeze it in in the next few days though.

**Comment by scottbelden** [comment]
@lemurchik I threw this together and maybe it's a good start as a benchmark? https://gist.github.com/scottbelden/23de56f57d1b6956e3620f0bf1c3fac7

Would you mind running that on your branch with and without `ujson` installed?

**Comment by lemurchik** [comment]
@scottbelden 
Without ujson
```
time python benchmark.py 

Writing 1 records to one file...
... 100000 runs averaged 4.46058750153e-05 seconds
Reading 1 records from one file...
... 100000 runs averaged 3.79474020004e-05 seconds

Writing 100 records to one file...
... 1000 runs averaged 0.000390723705292 seconds
Reading 100 records from one file...
... 1000 runs averaged 0.000404514074326 seconds

Writing 10000 records to one file...
... 10 runs averaged 0.0336557149887 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.0378547906876 seconds

Writing 1 records to one file...
... 100000 runs averaged 7.70504784584e-05 seconds
Reading 1 records from one file...
... 100000 runs averaged 8.6549539566e-05 seconds

Writing 100 records to one file...
... 1000 runs averaged 0.00225647449493 seconds
Reading 100 records from one file...
... 1000 runs averaged 0.00234637856483 seconds

Writing 10000 records to one file...
... 10 runs averaged 0.218417286873 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.241429257393 seconds

real	0m35,714s
user	0m35,056s
sys	0m0,624s
```

With ujson
```
time python benchmark.py 

Writing 1 records to one file...
... 100000 runs averaged 3.2373187542e-05 seconds
Reading 1 records from one file...
... 100000 runs averaged 3.03940439224e-05 seconds

Writing 100 records to one file...
... 1000 runs averaged 0.000373055458069 seconds
Reading 100 records from one file...
... 1000 runs averaged 0.000397135257721 seconds

Writing 10000 records to one file...
... 10 runs averaged 0.0337543964386 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.0369121313095 seconds

Writing 1 records to one file...
... 100000 runs averaged 7.25268721581e-05 seconds
Reading 1 records from one file...
... 100000 runs averaged 6.79690122604e-05 seconds

Writing 100 records to one file...
... 1000 runs averaged 0.00224966573715 seconds
Reading 100 records from one file...
... 1000 runs averaged 0.00231112122536 seconds

Writing 10000 records to one file...
... 10 runs averaged 0.219660139084 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.232347679138 seconds

real	0m31,246s
user	0m31,044s
sys	0m0,172s
```

**Comment by lemurchik** [comment]
Benchmarking with Cython

Without ujson
```
time python benchmark.py 

Writing 1 records to one file...
... 100000 runs averaged 1.81804084778e-05 seconds
Reading 1 records from one file...
... 100000 runs averaged 2.4766600132e-05 seconds

Writing 100 records to one file...
... 1000 runs averaged 9.3713760376e-05 seconds
Reading 100 records from one file...
... 1000 runs averaged 0.000203284502029 seconds

Writing 10000 records to one file...
... 10 runs averaged 0.00747935771942 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.0185041427612 seconds

Writing 1 records to one file...
... 100000 runs averaged 3.62542104721e-05 seconds
Reading 1 records from one file...
... 100000 runs averaged 5.9502453804e-05 seconds

Writing 100 records to one file...
... 1000 runs averaged 0.000551908254623 seconds
Reading 100 records from one file...
... 1000 runs averaged 0.00110595583916 seconds

Writing 10000 records to one file...
... 10 runs averaged 0.0497134685516 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.113085722923 seconds

real	0m18,094s
user	0m17,840s
sys	0m0,236s
```

With ujson
```
time python benchmark.py 

Writing 1 records to one file...
... 100000 runs averaged 1.36989378929e-05 seconds
Reading 1 records from one file...
... 100000 runs averaged 1.83930778503e-05 seconds

Writing 100 records to one file...
... 1000 runs averaged 0.000102315187454 seconds
Reading 100 records from one file...
... 1000 runs averaged 0.000203262090683 seconds

Writing 10000 records to one file...
... 10 runs averaged 0.00748679637909 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.0186181783676 seconds

Writing 1 records to one file...
... 100000 runs averaged 3.16268706322e-05 seconds
Reading 1 records from one file...
... 100000 runs averaged 4.082726717e-05 seconds

Writing 100 records to one file...
... 1000 runs averaged 0.000533112049103 seconds
Reading 100 records from one file...
... 1000 runs averaged 0.00111326551437 seconds

Writing 10000 records to one file...
... 10 runs averaged 0.0507858991623 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.112650609016 seconds

real	0m14,643s
user	0m14,436s
sys	0m0,188s
```

**Comment by scottbelden** [comment]
Thanks!

**Comment by barrywhart** [comment]
I know this has already been merged, but I'm wondering if we might want to use [`extras_require`](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) to specify `ujson` as an optional dependency.

Here's an [example](https://github.com/apache/incubator-airflow/blob/master/setup.py#L244) of a real-life project which uses it.

**Pull request merged**
