### PR TITLE
added abstract base classes to integral and float types

### PR DESCRIPTION
**Pull request by NightFantomJ2**
added abstract base classes to integral and float types in _write.validate, to support numpy types (and other classes that correctly register the abstract base classes), including tests

fixes part of https://github.com/tebeka/fastavro/issues/112, as per discussion there

### CODE REVIEW

**Comment by NightFantomJ2** [comment]
For those checks to succeed I probably need to add numpy somewhere in the config files? Can someone help me with that? Alternatively we can disable the numpy test and the other test will still confirm that all still works as intended.

I don't understand how pypy errors while the others don't
`AttributeError: module 'fastavro' has no attribute '_write'`
Should I access these in a different way? Or shouldn't I call validate like that?

**Comment by scottbelden** [comment]
To add numpy you should just need to add it to the [travis file](https://github.com/tebeka/fastavro/blob/master/.travis.yml#L11) and the [appveyor file](https://github.com/tebeka/fastavro/blob/master/appveyor.yml#L15). I created an issue just now so that when I find some time I can make this a little easier: https://github.com/tebeka/fastavro/issues/184.

For `validate`, you will need to add it to `write.py` like what is being done in https://github.com/tebeka/fastavro/pull/182: https://github.com/tebeka/fastavro/pull/182/files#diff-b775c6f9a6a096017db8a44fc0aad380R18. However, for the moment, I think it would be best to have it in that file as `_validate = _write.validate`. `validate` isn't really a public API and while it will become so in the other PR, I think it might make it's way into it's own module so let's leave an underscore until that gets figured out.

After that you should be able to change the test to do `fastavro.write._validate`.

**Comment by scottbelden** [comment]
Oh, and just for extra knowledge, the reason why you get `AttributeError: module 'fastavro' has no attribute '_write'` on pypy is because `fastavro._write` refers to this file (https://github.com/tebeka/fastavro/blob/master/fastavro/_write.pyx) which isn't compiled or accessible on pypy. It can get a little messy, but all the public functions should be accessed from [`fastavro.write`](https://github.com/tebeka/fastavro/blob/master/fastavro/write.py#L1-L4) which does an import check to use the cython files if they exist but fall back to pure python if they don't (which is the case for pypy).

**Comment by NightFantomJ2** [comment]
I'll see if I can do those fixes tonight.

Thanks for the clarifications, @scottbelden!

**Comment by scottbelden** [comment]
@NightFantomJ2 If you check the box to allow commits from maintainers I can make some updates to help get this through. Thanks!

**Comment by scottbelden** [comment]
Actually, I went ahead and pushed a new branch with your original commit and a commit to fix the issues. The PR is here: https://github.com/tebeka/fastavro/pull/189.

**Pull request closed without merging**
