### PR TITLE
Refactor writer as optional class

### PR DESCRIPTION
**Pull request by qix**
I'm using fastavro to write out large files (hundreds of mb+)

At that point the speed savings start becoming significant, but also I don't want to store the entire file in memory. Unfortunately the `writer()` api requires a list of records.

I refactored it to a class, with minimal changes. Unfortunately it requires that you call `.flush()` which is not an ideal api.

### CODE REVIEW

**Comment by tebeka** [comment]
Thanks @qix . However the `records` parameter to writer is an iterable. It doesn't have to be a list but can be a generator that produces records one at a time. Unless I'm missing something?

**Comment by qix** [comment]
Sure that would work as long writing a single avro file is the primary purpose of your application.

Writing any avro on the side, or for our case trying to write multiple files in parallel, is not supported.

**Comment by qix** [comment]
We're looking at open sourcing the project, but for now here is a dump of the code if you're interested:

https://github.com/qix/kafka-store-tmp/blob/master/kafka_store/handler.py

Essentially it reads from kafka on multiple partitions, and dumps each partition to an avro file in an efficient and atomic (only once) manor.

**Comment by tebeka** [comment]
By "parallel" do you mean multi-threading or several files each from a source?

I see in the example that you write records as they come. This can be done with a writer thread, something like the (untested) code below:

```python
from threading import Thread
from queue import Queue

queue = Queue()
Thread(target=fastavro.writer, args=(fo, schema, iter(queue.get, None), daemon=True).start()
```
Then push records to queue when they arrive. Signal done with pushing None to the queue.

Having said all that. I'm OK with merging your code - just make it pass the test suite first please :)

**Comment by qix** [comment]
I fought with the test suite a little bit. It looks like the problem is `flake8` dropped support for `python2.6`. I tried to force it to use the last supported version, but I'll open a seperate pull request for that.

You might just want to remove python2.6 from supported versions, but leave that up to you.

**Comment by qix** [comment]
(i.e. my change did not break them, they're currently failing in master.)

It'd be great if I could get this merged upstream.

**Pull request merged**
