### PR TITLE
UUID logical type support

### PR DESCRIPTION
**Pull request by kkirsanov**
UUID logical type is not a part of current specification (https://avro.apache.org/docs/1.8.1/spec.html)

But its support is already included in java codebase:
1) https://github.com/apache/avro/blob/17f2d75132021fafeca29edbdcade40df960fdc9/lang/java/avro/src/main/java/org/apache/avro/Conversions.java#L52
2) https://issues.apache.org/jira/browse/AVRO-1962?focusedCommentId=15688400&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15688400

java-generated avro file are included to tests.

### CODE REVIEW

**Comment by kkirsanov** [comment]
Strange that uuid is represented by a hex-string, not bytes. But that's exactly how it was done in Java and Scala.

**Comment by kkirsanov** [comment]
@tebeka can you help me with travis and python 3.4?

According to https://travis-ci.org/tebeka/fastavro/jobs/269259954 problem in datetime-micros, but I did not touch this part in this commit.

**Comment by tebeka** [comment]
Sure. I'll have a look.

**Comment by kkirsanov** [comment]
in python 3.4
'multi_union_time': datetime.datetime(2017, 8, 28, 17, 27, 21, 63992**0**)
vs
'multi_union_time': datetime.datetime(2017, 8, 28, 17, 27, 21, 63991**9**)


This can be result of https://github.com/tebeka/fastavro/pull/92 and datetime.now() in test data. So every time tests runs with different datetime and sometimes with a rounding error.

**Comment by kkirsanov** [comment]
By the way
This PR can be rplaced with:

```python
import fastavro

def read_uuid(data, writer_schema=None, reader_schema=None):
    return UUID(data)

def prepare_uuid(data, schema):
    return str(data)

fastavro._writer.LOGICAL_WRITERS['string-uuid']=prepare_uuid
fastavro._reader.LOGICAL_READERS['string-uuid']=read_uuid
```

**Comment by tebeka** [comment]
I'm merging this in, will check 3.4 problems later.

**Pull request merged**
