### PR TITLE
date-time logical types support

### PR DESCRIPTION
**Pull request by kkirsanov**
Processing avro`s logical types requires more complicaded dispatching.
To do this with minimal changes UserDict with custom getitem on READERS\WRITERS are used.

### CODE REVIEW

**Comment by tebeka** [comment]
Thanks @kkirsanov , why did you close this one?

**Comment by kkirsanov** [comment]
Cause i'm new to github and scared of multiple commits in one request :)

**Comment by tebeka** [comment]
Well, [you shouldn't](https://github.com/blog/2141-squash-your-commits) :)

**Comment by kkirsanov** [comment]
i have a new one - https://github.com/tebeka/fastavro/pull/79
now with decimal type

**Pull request closed without merging**
