### PR TITLE
handle error types

### PR DESCRIPTION
**Pull request by scottbelden**
The reader could already read error types but the writer was unable to serialize them.

### CODE REVIEW

**Comment by tebeka** [comment]
Thanks! Will merge soon-ish. (You're fast man :)

**Comment by scottbelden** [comment]
We've been using the standard avro library for a while and are looking to switch to this as it is indeed much faster. As a result we have schemas for almost everything and so just trying to get this to handle all of them.

**Comment by tebeka** [comment]
Are there any more in the pipeline? I'll hold of the release. If not will try to release early tomorrow (GMT+2)

**Comment by scottbelden** [comment]
Possibly. Also, I think I accidentally added an extra commit to this PR. Let me fix that.

**Pull request merged**
