### PR TITLE
For issue #130: Expose Writer class, add "dirty" property

### PR DESCRIPTION
**Pull request by barrywhart**
Can I get some preliminary feedback on this PR? It implements the first idea discussed in #130.

- [x] Expose `Writer` as a public class
- [x] Make `Writer`'s `.io` field expose a similar API in regular Python and Cython
- [x] Rerun writer performance benchmark to ensure no performance regressions
- [x] Add new tests for `Writer` now that it's public? (Would appreciate some suggestions on this.)

### CODE REVIEW

**Comment by barrywhart** [comment]
This PR:

```
Writing 10000 records to one file...
... 50 runs averaged 0.00858006954193 seconds
Reading 10000 records from one file...
... 50 runs averaged 0.0159693431854 seconds

Writing 10000 records to one file...
... 50 runs averaged 0.0575728607178 seconds
Reading 10000 records from one file...
... 50 runs averaged 0.0941914415359 seconds
```

Benchmark run from the original `_writer.pyx` PR:
```
Writing 10000 records to one file...
... 10 runs averaged 0.0102419137955 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.0207515954971 seconds

Writing 10000 records to one file...
... 10 runs averaged 0.0623118400574 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.121334815025 seconds
```

So the write performance still looks good.

**Comment by barrywhart** [comment]
I made a few changes based on the discussion so far:
* In `Writer`
  * Make most fields private (only in Cython version; Python doesn't support this)
  * Rename `dump()` as `_dump()` to imply it's private
  * Add a `dirty` property so it's possible to implement a cutoff without accessing `block_count` and `io` fields

With these changes, the file size cutoff can now be implemented externally as:
```
        writer.write(record)

        # Block count of zero indicates fastavro just reached an internal max
        # size and ran Writer.dump(). This is a good time to consider starting
        # a new file.
        if not writer.dirty and output_file.tell() >= MAX_FILE_SIZE:
                    output_file.close()
                    writer = Writer(...)
```

(I noticed the original example in the issue I filed was overly complex as well. I will clean that up for a fair comparison.)

**Comment by barrywhart** [comment]
Ok, I reverted the last 3 commits. I'd appreciate any guidance about what level and kind of testing and documentation would be appropriate for this PR.

Thanks!

**Comment by scottbelden** [comment]
This seems good to me. As for testing, I think something that just shows the basic use case would be sufficient for the moment. Something like:

```python
from fastavro.writer import Writer

writer = Writer(file, schema)
for record in records:
    writer.write(record)
writer.flush()

...
# read
...
assert read_records == records
```

This wouldn't test anything new (as the normal `writer` function basically already tests this) but I think would be useful as a proof of "this is basically how it would work"

**Comment by barrywhart** [comment]
I added 3 tests:
* Basic test that illustrates writing records and flushing
* Test that illustrates a useful scenario for unit testing code that uses `Writer`, where small files are preferable so tests run quickly. This test specifies a `sync_interval` of 0, which forces `Writer` to flush automatically after each record.
* Test that illustrates splitting a set of records across two files based on automatic flush behavior. This test approximates the real-world use case of splitting files when they exceed a target size.

**Comment by scottbelden** [comment]
Wow, nice tests. I'm good for merging. @tebeka do you have any thoughts?

**Comment by tebeka** [comment]
@scottbelden Sorry, way too busy this week. Whatever you decide is good for me.

**Pull request merged**
