### PR TITLE
Allow nested record definitions from arrays and maps.

### PR DESCRIPTION
**Pull request by mtth**
Also fix namespace bug for `union` references. (Added a test for each.)

Thanks for writing this great package!

### CODE REVIEW

**Comment by tebeka** [comment]
Thanks! Will check shortly and merge.

**Comment by wesm** [comment]
Why are the compiled files being checked in?

**Comment by rouge8** [comment]
:+1: this fixes some bugs I was going to track down

**Comment by mtth** [comment]
@wesm - Didn't look into it much but the README has this snippet:

> As recommended by Cython, the C files output is distributed. This has the advantage that the end user does not need to have Cython installed. However it means that every time you change fastavro/pyfastavro.py you need to run make.

**Comment by wesm** [comment]
The recommendation is for setup.py sdist, not git. See pandas and other modules implemented in large part in Cython

**Comment by virtuald** [comment]
+1

**Comment by tebeka** [comment]
Merged. Will leave the generated c files out of git.

**Pull request merged**
